-- Projects are the core of the portfolio. Section 6 of the spec defines this model.
-- Everything the public site shows about a project comes from here rather than
-- being hardcoded into the frontend.

CREATE TABLE projects (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug              VARCHAR(120)  NOT NULL,
    name              VARCHAR(200)  NOT NULL,
    short_description VARCHAR(500)  NOT NULL,
    long_description  TEXT,
    status            VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    featured          BOOLEAN       NOT NULL DEFAULT FALSE,
    github_url        VARCHAR(500),
    demo_url          VARCHAR(500),
    display_order     INTEGER       NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT uq_projects_slug UNIQUE (slug),
    CONSTRAINT ck_projects_status CHECK (status IN ('ACTIVE', 'ARCHIVED', 'IN_PROGRESS'))
);

-- The public list endpoint always sorts by display_order, and almost always
-- filters on status or featured. This index covers the common path.
CREATE INDEX idx_projects_listing ON projects (status, featured, display_order);
