-- Section 8. A lightweight technical blog, mostly so there is a second content
-- type for search and caching to work across.

CREATE TABLE blog_posts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug         VARCHAR(160)  NOT NULL,
    title        VARCHAR(250)  NOT NULL,
    summary      VARCHAR(600),
    content      TEXT          NOT NULL,
    status       VARCHAR(20)   NOT NULL DEFAULT 'DRAFT',
    published_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT uq_blog_posts_slug UNIQUE (slug),
    CONSTRAINT ck_blog_posts_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),

    -- A published post without a publication date would sort unpredictably on
    -- the public listing, so the database refuses that state outright.
    CONSTRAINT ck_blog_posts_published_has_date
        CHECK (status <> 'PUBLISHED' OR published_at IS NOT NULL)
);

CREATE INDEX idx_blog_posts_published ON blog_posts (status, published_at DESC);

-- Deliberately NOT indexed yet.
--
-- Section 18 wants PostgreSQL full-text search and section 62 wants a
-- before-and-after measurement of adding a GIN index. Creating the search
-- vector now but leaving it unindexed means the "340 ms -> 28 ms" story can be
-- measured for real later instead of asserted. The GIN index arrives with the
-- search module.
ALTER TABLE blog_posts
    ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce(title, '')),   'A') ||
        setweight(to_tsvector('english', coalesce(summary, '')), 'B') ||
        setweight(to_tsvector('english', coalesce(content, '')), 'C')
    ) STORED;
