-- Section 10. Metadata mirrored from the GitHub API.
--
-- This table is a cache with a database behind it, not a source of truth. It
-- must always hold the last values that were successfully fetched, because the
-- whole point of section 12 is that the site keeps working when GitHub does
-- not. Nothing here is ever cleared on a failed sync — only sync_status and
-- last_synced_at move.

CREATE TABLE github_repositories (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id       BIGINT       NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    owner            VARCHAR(120) NOT NULL,
    repository       VARCHAR(200) NOT NULL,
    stars            INTEGER      NOT NULL DEFAULT 0,
    forks            INTEGER      NOT NULL DEFAULT 0,
    open_issues      INTEGER      NOT NULL DEFAULT 0,
    primary_language VARCHAR(80),
    last_commit_at   TIMESTAMPTZ,
    last_release     VARCHAR(120),
    last_synced_at   TIMESTAMPTZ,
    sync_status      VARCHAR(20)  NOT NULL DEFAULT 'PENDING',

    -- One repository per project: the join in ProjectService assumes it, and
    -- two rows for one project would make "the stars for this project"
    -- ambiguous.
    CONSTRAINT uq_github_repositories_project UNIQUE (project_id),
    CONSTRAINT uq_github_repositories_slug UNIQUE (owner, repository),
    CONSTRAINT ck_github_sync_status
        CHECK (sync_status IN ('PENDING', 'OK', 'FAILED', 'RATE_LIMITED'))
);

-- Link the seeded projects to their repositories. Values stay at their
-- defaults until the first sync runs; PENDING is what "never fetched" looks
-- like, and is distinct from FAILED.
INSERT INTO github_repositories (project_id, owner, repository)
SELECT p.id, r.owner, r.repository
FROM projects p
JOIN (VALUES
    ('navigation-assistant', 'swjk1', 'Navigation-assistant-for-visually-impaired'),
    ('keyguard',             'swjk1', 'keyguard'),
    ('cookpilot',            'swjk1', 'CookBot')
) AS r(slug, owner, repository) ON r.slug = p.slug;
